Development
tp17-2021/statistics-frontend pull request #1
Opened 2022-04-27 12:24 UTC by denis116

ts refactor, vyriesenie bugov, doladenie detailov

2022-05-01 18:30 UTC, celuchmarek commented
Ten refresh button chceme nechať?

Percentá sa nedajú dať na tie dve desatiné miesta?

Footer necháme jak je?

@denis116, toto je podľa mňa už aj posledný PR a potom necháme toto repo asi nedoknuté ďalším generáciám. Daj odpovede na tie tri otázky a potom možno approvenem.

2022-05-01 18:31 UTC, celuchmarek requested changes
Ten refresh button chceme nechať?

Percentá sa nedajú dať na tie dve desatiné miesta?

Footer necháme jak je?

@denis116, toto je podľa mňa už aj posledný PR a potom necháme toto repo asi nedoknuté ďalším generáciám. Daj odpovede na tie tri otázky a potom možno approvenem.

2022-05-01 18:38 UTC, denis116 commented
Refresh button asi netreba kedže ak bude este nejaka interaktivna ukazka tak staci refreshnut stranku, percenta na dve sa daju spravit, zajtra sa na to pozriem a paticku asi nieco pridat treba nech to je realnejsie. Tak zatial nemerguj.

2022-05-18 09:27 UTC, celuchmarek approved these changes

2022-05-18 09:27 UTC, merged